### PR TITLE
Made all parameters optional aside from ID.

### LINKED ISSUE #10: Name parameter not working
version 1.3.2,
config:

> {
>     "platform": "RadioRA2",
>     "name": "RadioRA2",
>     "repeater": "redacted",
>     "username": "redacted",
>     "password": "redacted",
>     "fans": [
>         {
>             "name": "Master Bedroom Fan",
>             "id": 18,
>             "adjustable": true,
>             "onvalue": 25
>         },
>         {
>             "name": "Den Fan",
>             "id": 35,
>             "adjustable": true,
>             "onvalue": 25
>         }
>     ],
>     "occupancysensors": [
>         {
>             "name": "Master Closet Occupancy",
>             "id": 25
>         }
>     ]
> }

In the logs I get:

> [10/31/2021, 3:45:40 PM] [RadioRA2] Connected to Lutron!
> (node:2141) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
>     at new Fan (/homebridge/node_modules/homebridge-radiora2/lib/accessories/fan.js:14:72)
>     at RadioRA2Platform.addFanAccessory (/homebridge/node_modules/homebridge-radiora2/index.js:57:44)
>     at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:211:30)
>     at Array.forEach (<anonymous>)
>     at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:206:23)
>     at RadioRa2.emit (events.js:400:28)
>     at incomingData (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:97:20)
>     at Socket.<anonymous> (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:27:92)
>     at Socket.emit (events.js:400:28)
>     at addChunk (internal/streams/readable.js:293:12)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:2141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

If I remove the "name" entries I get the following:

> [10/31/2021, 3:52:04 PM] [RadioRA2] Connected to Lutron!
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid fan in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid fan in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 2 fan(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 light(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid occupancy sensor in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 1 occupancy sensor(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 keypad(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 visor control receiver(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 HVAC controller(s)

### PR DESCRIPTION
**Pull request by cariacou**
- Fixed a bug where `model` was required (unfortunate call to `toString`)
- Fixed a bug where some `Fans` were being declared as `Lights`
- Made all parameters optional aside from ID (`name`, etc)
- Updated the readme accordingly

Fixes #10

### CODE REVIEW

**Comment by senorshaun** [comment]
I’m fine merging all this if you have tested, I’ll merge and then push to npm. 
Only question I have is about the fan/light bug? Can you give me some more info

On Dec 12, 2021, at 2:00 PM, cariacou ***@***.***> wrote:

﻿
Fixed a bug where model was required (unfortunate call to toString)
Fixed a bug where some Fans were being declared as Lights
Made all parameters optional aside from ID (name, etc)
Updated the readme accordingly
You can view, comment on, or merge this pull request online at:

  https://github.com/senorshaun/homebridge-radiora2/pull/11

Commit Summary

6495a14 Made all parameters optional aside from ID.
File Changes  (11 files)
M README.md (7)
M index.js (16)
M lib/accessories/fan.js (12)
M lib/accessories/hvaccontroller.js (6)
M lib/accessories/keypadbutton.js (9)
M lib/accessories/lightbulb.js (6)
M lib/accessories/occupancysensor.js (4)
M lib/accessories/statelessswitch.js (6)
M lib/accessories/visorcontrolreceiver.js (8)
M lib/radiora2.js (4)
M package.json (78)
Patch Links:

https://github.com/senorshaun/homebridge-radiora2/pull/11.patch
https://github.com/senorshaun/homebridge-radiora2/pull/11.diff
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

File: index.js [hunk 1]
```diff
@@ -204,8 +212,9 @@ class RadioRA2Platform {
             // Fans
             let fansArray = this.config.fans || [];
             fansArray.forEach(function (fanConfig) {
+		fanConfig = addDefaultValues(fanConfig, "Fan");
                 if ((fanConfig.id) && (fanConfig.name)) {
-                    var uuid = UUIDGen.generate("light:" + fanConfig.id);
```
Comment (cariacou) [inline index.js:208]: fan miscategorized as light here

**Comment by cariacou** [comment]
I've tested it with fans (only thing I am importing in my setup). 
I am assuming you would be in charge of releasing `homebridge-radiora2-1.3.3.tgz` ? This is my first commit here

**Comment by senorshaun** [comment]
Oh ok. That’s not actually categorizing as light, that’s just how the unique identifier is created for the device. Good catch though.  

On Dec 12, 2021, at 2:36 PM, cariacou ***@***.***> wrote:

﻿
@cariacou commented on this pull request.

In index.js:

>                  if ((fanConfig.id) && (fanConfig.name)) {
-                    var uuid = UUIDGen.generate("light:" + fanConfig.id);
fan miscategorized as light here

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
